/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_afeskov_defironsource_IronSourceWrapper */

#ifndef _Included_com_afeskov_defironsource_IronSourceWrapper
#define _Included_com_afeskov_defironsource_IronSourceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdOpened
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdOpened
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdClosed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdClosed
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAvailabilityChanged
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAvailabilityChanged
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdStarted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdStarted
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdEnded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdEnded
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdRewarded
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdRewarded
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdShowFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdShowFailed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onRewardedVideoAdClicked
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onRewardedVideoAdClicked
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdReady
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdReady
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdLoadFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdLoadFailed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdOpened
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdOpened
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdClosed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdClosed
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdShowSucceeded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdShowSucceeded
  (JNIEnv *, jclass);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdShowFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdShowFailed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_afeskov_defironsource_IronSourceWrapper
 * Method:    onInterstitialAdClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afeskov_defironsource_IronSourceWrapper_onInterstitialAdClicked
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
